# This is a basic workflow to help you get started with Actions

name: mssql_server_2017-cu20-ubuntu-16.04

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ mssql ]
  pull_request:
    branches: [ mssql ]
  
env: 
  MCR_IMAGE_PATH:  mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04 
  ALIYUN_IMAGE_PATH: registry.cn-shanghai.aliyuncs.com/yomunsam/microsoft-mssql-server:2017-CU20-ubuntu-16.04 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # 处理各个Docker Registry的登录
    - name: Login Registrys
      run: |
        echo "Login Aliyun Docker Registry" | docker login --username=${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }} --password-stdin registry.cn-shanghai.aliyuncs.com
      
    # 拉取镜像
    - name: Pull Image
      run: |
        echo "Pull Image $MCR_IMAGE_PATH"
        docker pull $MCR_IMAGE_PATH
    
    # 推镜像
    - name: Push Image
      run: |
        echo "Push to Aliyun"
        docker tag  $MCR_IMAGE_PATH $ALIYUN_IMAGE_PATH
        docker push $ALIYUN_IMAGE_PATH
        
        

    
