# This is a basic workflow to help you get started with Actions

name: aspnet-3.1-alpine3.12

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ aspnet ]
  pull_request:
    branches: [ aspnet ]
  workflow_dispatch:  
  
env: 
  MCR_IMAGE_PATH:  mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine3.12
  DOCKER_HUB_IMAGE_PATH: nekonya/mcr-aspnet:3.1-alpine3.12
  ALIYUN_IMAGE_PATH: registry.cn-shanghai.aliyuncs.com/nekonya/mcr-aspnet:3.1-alpine3.12

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # 处理各个Docker Registry的登录
    - name: Login Registrys
      run: |
        echo "登录到Docker Hub" | docker login --username=${{ secrets.DOCKER_HUB_USERNAME }} --password=${{ secrets.DOCKER_HUB_PASSWORD }}
        echo "登录到阿里云 Docker Registry" | docker login --username=${{ secrets.ALIYUN_DOCKER_REGISTRY_USERNAME }} --password=${{ secrets.ALIYUN_DOCKER_REGISTRY_PASSWORD }} registry.cn-shanghai.aliyuncs.com
      

    # 拉取镜像
    - name: Pull Image
      run: |
        echo "Pull Image $MCR_IMAGE_PATH"
        docker pull $MCR_IMAGE_PATH
    
    # 推镜像到Docker Hub
    - name: Push Image To Docker Hub
      run: |
        echo "Push to Docker Hub"
        docker tag  $MCR_IMAGE_PATH $DOCKER_HUB_IMAGE_PATH
        docker push $DOCKER_HUB_IMAGE_PATH

    # 推镜像到阿里云
    - name: Push Image To Aliyun
      run: |
        echo "Push to Aliyun"
        docker tag  $MCR_IMAGE_PATH $ALIYUN_IMAGE_PATH
        docker push $ALIYUN_IMAGE_PATH
        
        

    
